/*
 * Platform  API Manager
 * Platform- g2_sn_node_data_rsAPI
 *
 * OpenAPI spec version: Apache 2.0 License
 * Contact: supportsofia2@indra.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.miot.sn.mqtt.onesait.swagger.client;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-12T10:47:57.302Z")
public class Configuration {
	private static ApiClient defaultApiClient = new ApiClient();

	/**
	 * Get the default API client, which would be used when creating API instances
	 * without providing an API client.
	 *
	 * @return Default API client
	 */
	public static ApiClient getDefaultApiClient() {
		return defaultApiClient;
	}

	/**
	 * Set the default API client, which would be used when creating API instances
	 * without providing an API client.
	 *
	 * @param apiClient API client
	 */
	public static void setDefaultApiClient(ApiClient apiClient) {
		defaultApiClient = apiClient;
	}
}
