/*
 * Platform  API Manager
 * Platform- g2_sn_node_data_rsAPI
 *
 * OpenAPI spec version: Apache 2.0 License
 * Contact: supportsofia2@indra.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.miot.sn.mqtt.onesait.swagger.client;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-12T10:47:57.302Z")
public class Pair {
	private String name = "";
	private String value = "";

	public Pair(String name, String value) {
		setName(name);
		setValue(value);
	}

	private void setName(String name) {
		if (!isValidString(name)) {
			return;
		}

		this.name = name;
	}

	private void setValue(String value) {
		if (!isValidString(value)) {
			return;
		}

		this.value = value;
	}

	public String getName() {
		return this.name;
	}

	public String getValue() {
		return this.value;
	}

	private boolean isValidString(String arg) {
		if (arg == null) {
			return false;
		}
		if (arg.trim().isEmpty()) {
			return false;
		}

		return true;
	}
}
