/*
 * Platform  API Manager
 * Platform- g2_sn_node_data_rsAPI
 *
 * OpenAPI spec version: Apache 2.0 License
 * Contact: supportsofia2@indra.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.miot.sn.mqtt.onesait.swagger.client.auth;

import java.util.List;
import java.util.Map;

import com.miot.sn.mqtt.onesait.swagger.client.Pair;

public interface Authentication {
	/**
	 * Apply authentication settings to header and query params.
	 *
	 * @param queryParams  List of query parameters
	 * @param headerParams Map of header parameters
	 */
	void applyToParams(List<Pair> queryParams, Map<String, String> headerParams);
}
